### PR TITLE
Compare differently-qualified SumTypes correctly

### PR DESCRIPTION
**Pull request by pbackus**
Supersedes #41

### CODE REVIEW

**Comment by FeepingCreature** [comment]
`typeof(cast() value)` though please.

**Comment by pbackus** [comment]
That's what the template constraint is for.

**Comment by FeepingCreature** [comment]
... Okay, I don't get it. Isn't the template constraint equivalent to just taking the same type?

**Comment by pbackus** [comment]
> You can't have const types in a sumtype anyway

Of course you can. Why wouldn't you be able to?

**Comment by FeepingCreature** [comment]
.. Hm, I recall hitting some bug with it but I can't repro it offhand. I'll get you a bug report for that once I'm at my work computer.

**Comment by pbackus** [comment]
Yeah, you've got it now. I definitely need to go into more detail in the comments, though, if it's this tricky to understand.

**Pull request merged**
