### PR TITLE
Change License from MIT to Boost

### PR DESCRIPTION
**Pull request by pbackus**
This is a requirement for submitting sumtype to Phobos[1], which I plan to do after the 1.0 release.

Because the Boost Software License is not compatible with the MIT license (it is more permissive), I need the permission of *all* contributors to `sumtype` in order to make this change. If your Github handle is listed below, and you wish to give your permission for this change, please say so in a reply to this pull request.

@atilaneves @geezee @wilzbach 

[1] https://wiki.dlang.org/Review/Process#Requirements

### CODE REVIEW

**Review by wilzbach — APPROVED** [review]
Awesome!

**Comment by atilaneves** [comment]
Permission granted.

**Comment by geezee** [comment]
Permission granted

**Comment by pbackus** [comment]
Thanks everyone!

**Pull request merged**
