### PR TITLE
Avoid generating lots of small temporary functions.

### PR DESCRIPTION
**Pull request by FeepingCreature**
- Move destructor lambda into global scope (allow instance reuse)
- Move `stride` template into global scope (allow instance reuse)
- `getValues` yields a string of an argument list instead of a value tuple.

Effects:

- slightly slower in normal operation
- enormously faster in degenerate cases (large number of types, `-O -inline`) due to avoiding overloading the inliner
- smaller object file size.

To reproduce the degenerate case, try with this test program (remember `-O -inline`):

```
module test;

import std;
import sumtype;

struct S(int i) { }

void main() {
    alias mega = SumType!(staticMap!(S, aliasSeqOf!(15.iota)));
    mega.init == mega.init;
}
```

Adjust the iota to make things slower. Note that we have a 21-type SumType in practice - this is not academic! If you set iota to 21, then in the stock 1.0.0 version the optimizer will run for at least five minutes. (At least that's where I gave up.)

### CODE REVIEW

**Comment by pbackus** [comment]
The changes to `getValue` fail when compiling with `-betterC`. This should have been caught automatically, but there was a typo in my Github Actions workflow (now fixed) preventing tests from being run on PRs. You can test your changes locally with `test-betterc.sh`.

**Comment by FeepingCreature** [comment]
The lack of `format!` and `join` really hurts, even at compiletime. Seems to work now though.

**Comment by pbackus** [comment]
Tagged as `v1.0.1`. Thanks a lot!

**Comment by pbackus** [comment]
This PR introduced a regression (#65).

**Pull request merged**
